### ISSUE TITLE
Note10+ Android 10 reset number when rotate face

### ISSUE THREAD

**Issue by duonghv97** [vnptekyc/ekyc-android-sdk-samples#3]
I'm on Note 10 + with Android 10, but when I turn my face the number reset. Only my phone is affected. I can't scan face

**Comment by ngocphung247** [comment]
Please disable animation increase deletion for note10+. Follow this link:
![2020-08-12 16 07 24](https://user-images.githubusercontent.com/34225690/89997170-fbce1600-dcb5-11ea-8c1f-aee25b4b5ff8.jpg)
+.

**Comment by duonghv97** [comment]
I can scan face. 
Thank you so much!
